before:
  hooks:
    - go mod tidy

builds:
  - id: windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
  - id: linux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  disable: true

changelog:
  skip: true